# Generated by Django 4.1.2 on 2022-10-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='devices', to='devices.device'),
        ),
    ]
