# Generated by Django 4.1.2 on 2022-10-13 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
