# Generated by Django 4.1.2 on 2022-10-09 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uninstall_code',
            field=models.CharField(default=uuid.UUID('9b5c2397-affe-466d-9dbf-fae5e6297811'), max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a93bcd0c-af1d-4f81-88b3-e243495a4559'), max_length=255, unique=True),
        ),
    ]
