# Generated by Django 4.1.2 on 2022-10-07 22:11

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=devices.models.get_random_code, max_length=8, null=True),
        ),
    ]
