# Generated by Django 4.1.2 on 2022-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_screenshot_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='exec_name',
            field=models.TextField(default='Uknown Executable Name'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='title',
            field=models.TextField(default='Uknown Title'),
        ),
    ]
