# Generated by Django 4.1.2 on 2022-10-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='exec_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenshot',
            name='nsfw_detections',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='profane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='title',
            field=models.TextField(default='jk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
