# Generated by Django 4.1.2 on 2022-10-07 22:11

from django.db import migrations, models
import devices.models

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('devices', 'Device')
    for row in MyModel.objects.all():
        row.uuid = devices.models.get_random_code()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_uuid'),
    ]
    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]