# Generated by Django 4.1.2 on 2022-10-07 22:11

from django.db import migrations , models
from devices.models import get_random_code


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20221007_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=get_random_code, max_length=8, unique=True),
        ),
    ]
