# Generated by Django 4.1.2 on 2022-10-09 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20221007_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=uuid.UUID('186a32ee-4517-4807-9238-089ed37d44a5'), max_length=255, unique=True),
        ),
    ]
