# Generated by Django 4.1.2 on 2022-10-09 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=uuid.UUID('93e347e6-19c8-4c7d-b083-f33b6ef789a1'), max_length=255, unique=True),
        ),
    ]
