# Generated by Django 4.1.2 on 2022-10-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_confirmed_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='devices',
        ),
    ]
